# Generated by Django 4.2 on 2024-07-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('mensaje_cifrado', models.TextField(default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
