# Generated by Django 4.2 on 2024-07-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_pelicula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
